SELECT
	STUDENTS.lastfirst,
	SCHOOLS.name,
	(
		SELECT DISTINCT sch.NAME
		FROM CC JOIN SCHOOLS sch ON CC.SCHOOLID = sch.SCHOOL_NUMBER
		WHERE CC.STUDENTID = STUDENTS.id AND STUDENTS.SCHOOLID != CC.SCHOOLID AND CC.TERMID >= 3000
	) AS "Remote School",
	CASE 
		WHEN STUDENTS.track LIKE 'A' THEN 'In-Person'
		WHEN STUDENTS.track LIKE 'B' THEN 'Remote'
		WHEN STUDENTS.track LIKE 'C' THEN 'Online'
		ELSE STUDENTS.track
	END
	
	
FROM
	STUDENTS
	JOIN SCHOOLS ON STUDENTS.schoolid = SCHOOLS.school_number
	
WHERE 
	STUDENTS.enroll_status = 0